version: '3'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=your_database_url_here
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - ./client:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
